# Generated by Django 4.0.2 on 2023-11-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='date_of_birth',
            new_name='joindate',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='otp',
        ),
        migrations.AddField(
            model_name='user_registration',
            name='addres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='pro_pic',
            field=models.ImageField(default='static/images/logo/icon.png', upload_to='images/propic'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='role',
            field=models.CharField(blank=True, choices=[('user1', 'Staff'), ('user2', 'User')], max_length=255, null=True),
        ),
    ]
