# Generated by Django 4.0.2 on 2023-11-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0002_rename_date_of_birth_user_registration_joindate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
