# Generated by Django 4.0.2 on 2023-11-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0003_user_registration_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
