# Generated by Django 4.0.2 on 2023-11-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0004_user_registration_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='otp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
