# Generated by Django 4.0.2 on 2023-11-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0005_checkout_delivery_date_checkout_otp_checkout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='staff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
