# Generated by Django 4.0.2 on 2023-11-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0006_checkout_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='access',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
